add_executable(IntKeySimpleBSTTests tst_intkeysimplebsttests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp)
add_test(NAME IntKeySimpleBSTTests COMMAND IntKeySimpleBSTTests)

add_executable(IntKeyRedBlackTreesTests tst_intkeyredblacktreestests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp)
add_test(NAME IntKeyRedBlackTreesTests COMMAND IntKeyRedBlackTreesTests)

add_executable(IntKeyAVLTreesTests tst_intkeyavltreestests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp)
add_test(NAME IntKeyAVLTreesTests COMMAND IntKeyAVLTreesTests)

add_executable(IntKeyMixedTreeTypesTests tst_intkeymixedtreetypestests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp)
add_test(NAME IntKeyMixedTreeTypesTests COMMAND IntKeyMixedTreeTypesTests)

target_compile_definitions(IntKeySimpleBSTTests PRIVATE PRINT_TREE)
target_compile_definitions(IntKeyRedBlackTreesTests PRIVATE PRINT_TREE)
target_compile_definitions(IntKeyAVLTreesTests PRIVATE PRINT_TREE)
target_compile_definitions(IntKeyMixedTreeTypesTests PRIVATE PRINT_TREE)

target_link_libraries(IntKeySimpleBSTTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(IntKeySimpleBSTTests PRIVATE BSTLib)

target_link_libraries(IntKeyRedBlackTreesTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(IntKeyRedBlackTreesTests PRIVATE BSTLib)

target_link_libraries(IntKeyAVLTreesTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(IntKeyAVLTreesTests PRIVATE BSTLib)

target_link_libraries(IntKeyMixedTreeTypesTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(IntKeyMixedTreeTypesTests PRIVATE BSTLib)
