add_executable(StrIntKeySimpleBSTTests tst_strintkeysimplebsttests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp ${TEST_UTILITIES_DIR}/stringifiedinteger.cpp)
add_test(NAME StrIntKeySimpleBSTTests COMMAND StrIntKeySimpleBSTTests)

add_executable(StrIntKeyRedBlackTreesTests tst_strintkeyredblacktreestests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp ${TEST_UTILITIES_DIR}/stringifiedinteger.cpp)
add_test(NAME StrIntKeyRedBlackTreesTests COMMAND StrIntKeyRedBlackTreesTests)

add_executable(StrIntKeyAVLTreesTests tst_strintkeyavltreestests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp ${TEST_UTILITIES_DIR}/stringifiedinteger.cpp)
add_test(NAME StrIntKeyAVLTreesTests COMMAND StrIntKeyAVLTreesTests)

add_executable(StrIntKeyMixedTreeTypesTests tst_strintkeymixedtreetypestests.cpp ${TEST_UTILITIES_DIR}/testutils.cpp ${TEST_UTILITIES_DIR}/stringifiedinteger.cpp)
add_test(NAME StrIntKeyMixedTreeTypesTests COMMAND StrIntKeyMixedTreeTypesTests)

target_compile_definitions(StrIntKeySimpleBSTTests PRIVATE PRINT_TREE)
target_compile_definitions(StrIntKeyRedBlackTreesTests PRIVATE PRINT_TREE)
target_compile_definitions(StrIntKeyAVLTreesTests PRIVATE PRINT_TREE)
target_compile_definitions(StrIntKeyMixedTreeTypesTests PRIVATE PRINT_TREE)

target_link_libraries(StrIntKeySimpleBSTTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(StrIntKeySimpleBSTTests PRIVATE BSTLib)

target_link_libraries(StrIntKeyRedBlackTreesTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(StrIntKeyRedBlackTreesTests PRIVATE BSTLib)

target_link_libraries(StrIntKeyAVLTreesTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(StrIntKeyAVLTreesTests PRIVATE BSTLib)

target_link_libraries(StrIntKeyMixedTreeTypesTests PRIVATE Qt${QT_VERSION_MAJOR}::Test)
target_link_libraries(StrIntKeyMixedTreeTypesTests PRIVATE BSTLib)
